name: 'Packages Split'

on:
  push:
    branches:
      - main
      - master
    tags:
      - '*'

env:
  # 1. for GitHub split
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  packages_split:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # define package to repository map
        package:
          -
            path: 'module-tag'
            repo: 'module-tag-test'
          -
            path: 'module-tax'
            repo: 'module-tax-test'

    steps:
      -   uses: actions/checkout@v3

      - name: Mark github workspace as safe
        run: |
          git config --global --add safe.directory /github/workspace
          git config --global --add safe.directory /tmp/monorepo_split/build_directory

      # no tag
      -
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: "symplify/monorepo-split-github-action@2.1"
        with:
          # ↓ split "packages/easy-coding-standard" directory
          package_directory: 'packages/${{ matrix.package.path }}'

          # ↓ into https://github.com/openmage-strict/<REPO> repository
          repository_organization: 'openmage-strict'
          repository_name: '${{ matrix.package.repo }}'

      # with tag
      -
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: "symplify/monorepo-split-github-action@2.1"
        with:
          tag: ${GITHUB_REF#refs/tags/}

          # ↓ split "packages/easy-coding-standard" directory
          package_directory: 'packages/${{ matrix.package.path }}'

          # ↓ into https://github.com/openmage-strict/<REPO> repository
          repository_organization: 'openmage-strict'
          repository_name: '${{ matrix.package.repo }}'
